### ISSUE TITLE
Cannot read property 'languageIds' of undefined

### ISSUE THREAD

**Issue by mickaelistria** [TypeFox/ls-api#47]
Using language server for JSon from VSCode, I get:

```
java.util.concurrent.ExecutionException: io.typefox.lsapi.services.transport.InvalidMessageException: Request initialize failed with message: Cannot read property 'languageIds' of undefined
    at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:357)
    at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1895)
    at org.eclipse.languageserver.ProjectSpecificLanguageServerWrapper$5.run(ProjectSpecificLanguageServerWrapper.java:180)
    at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
Caused by: io.typefox.lsapi.services.transport.InvalidMessageException: Request initialize failed with message: Cannot read property 'languageIds' of undefined
    at io.typefox.lsapi.services.transport.client.LanguageClientEndpoint$RequestHandler.convertResult(LanguageClientEndpoint.xtend:366)
    at io.typefox.lsapi.services.transport.client.LanguageClientEndpoint$RequestHandler.get(LanguageClientEndpoint.xtend:361)
    at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
java.util.concurrent.TimeoutException
    at java.util.concurrent.CompletableFuture.timedGet(CompletableFuture.java:1771)
    at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1915)
    at org.eclipse.languageserver.operations.hover.LSBasedHover.getHoverRegion(LSBasedHover.java:82)
    at org.eclipse.jface.text.TextViewerHoverManager.computeInformation(TextViewerHoverManager.java:138)
    at org.eclipse.jface.text.AbstractInformationControlManager.doShowInformation(AbstractInformationControlManager.java:1144)
    at org.eclipse.jface.text.AbstractHoverInformationControlManager$MouseTracker.mouseHover(AbstractHoverInformationControlManager.java:518)
    at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:209)
    at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
    at org.eclipse.swt.widgets.Display.sendEvent(Display.java:5219)
    at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1340)
    at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4553)
    at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4143)
    at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$4.run(PartRenderingEngine.java:1121)
    at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
    at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1022)
    at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:150)
    at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:687)
    at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
    at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:604)
    at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:148)
    at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:138)
    at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
    at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
    at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
    at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
    at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:673)
    at org.eclipse.equinox.launcher.Main.basicRun(Main.java:610)
    at org.eclipse.equinox.launcher.Main.run(Main.java:1519)
    at org.eclipse.equinox.launcher.Main.main(Main.java:1492)
```

**Comment by mickaelistria** [comment]
Here is the full communication

```
WRITE: 
{"id":"0","method":"initialize","params":{"rootPath":"/home/mistria/runtime-EclipseApplication-with-patch/demo","capabilities":{},"clientName":"Eclipse IDE"},"jsonrpc":"2.0"}
RequestMessageImpl [
  id = "0"
  method = "initialize"
  params = InitializeParamsImpl [
    processId = null
    rootPath = "/home/mistria/runtime-EclipseApplication-with-patch/demo"
    capabilities = ClientCapabilitiesImpl [
    ]
    clientName = "Eclipse IDE"
  ]
  jsonrpc = "2.0"
]

READ: 
{"jsonrpc":"2.0","id":"0","error":{"code":-32603,"message":"Request initialize failed with message: Cannot read property 'languageIds' of undefined"}}
ResponseMessageImpl [
  id = "0"
  result = null
  error = ResponseErrorImpl [
    code = InternalError
    message = "Request initialize failed with message: Cannot read property 'languageIds' of undefined"
    data = null
  ]
  jsonrpc = "2.0"
]

java.util.concurrent.ExecutionException: io.typefox.lsapi.services.transport.InvalidMessageException: Request initialize failed with message: Cannot read property 'languageIds' of undefined
    at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:357)
    at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1895)
    at org.eclipse.languageserver.ProjectSpecificLanguageServerWrapper$2.run(ProjectSpecificLanguageServerWrapper.java:196)
    at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
Caused by: io.typefox.lsapi.services.transport.InvalidMessageException: Request initialize failed with message: Cannot read property 'languageIds' of undefined
    at io.typefox.lsapi.services.transport.client.LanguageClientEndpoint$RequestHandler.convertResult(LanguageClientEndpoint.xtend:366)
    at io.typefox.lsapi.services.transport.client.LanguageClientEndpoint$RequestHandler.get(LanguageClientEndpoint.xtend:361)
    at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
```

There is no mention about such `languageIds` field in the language server protocol.
It works fine with OmniSharp, so it seems to be VSCode-specific. Or is ls-api hiding the underlying server response?

@dbaeumer: is this kind of report for VSCode familiar? Do you have a clue about how to troubleshoot it?

**Comment by svenefftinge** [comment]
There was an optional non-supported extension to the InitializeResponse I removed now.

**Comment by mickaelistria** [comment]
Submitted patch cause 1 test to fail and prevents build from continuing (and p2 repo from being published)

**Comment by svenefftinge** [comment]
oops sorry, I still need to get used to actively call the 'test' task in gradle. It's fixed and published now.

**Comment by mickaelistria** [comment]
Gradle doesn't run tests by default!? That goes against all principles of CI. Yet another reason for me to dislike it!
Anyway, things are working great now, thanks.
