### ISSUE TITLE
Missing header Content-Length

### ISSUE THREAD

**Issue by georgewfraser** [TypeFox/ls-api#6]
I get the following error:

```
java.lang.IllegalStateException: Missing header Content-Length in input "{"jsonrpc":"2.0","method":"textDocument/didChange","params":{"textDocument":{"uri":"file:///Users/george/Documents/vscode-javac/src/main/java/org/javacs/JavaLanguageServer.java","version":28},"contentChanges":[{"text":"<giant multiline text>"}]}}Content-Length: 178

"
    at io.typefox.lsapi.json.LanguageServerProtocol.listen(LanguageServerProtocol.java:156)
    at io.typefox.lsapi.json.LanguageServerProtocol$InputListener.run(LanguageServerProtocol.java:59)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
```

I have replaced the contents of textDocument with `<giant multiline text>` for readability.

**Comment by georgewfraser** [comment]
Once this error happens once, it happens constantly. Seems like the interpretation of the incoming bytes has gotten out of alignment somehow.

**Comment by georgewfraser** [comment]
I switched to incremental text document synchronization and the problem hasn't recurred, but I suspect that underlying issues is still there but masked somehow.

**Comment by spoenemann** [comment]
Could you provide the full input stream as a text file, including all previous messages?

**Comment by georgewfraser** [comment]
This is still happening, with 0.2-SNAPSHOT, with incremental TextDocument synchronization.

Does ls-api log this input stream somewhere?

**Comment by georgewfraser** [comment]
This error seems to occur first:

com.google.gson.stream.MalformedJsonException: Unterminated string at line 1 column 32132 path $.params.contentChanges[0].text

**Comment by georgewfraser** [comment]
Getting closer:

```
SEVERE  ?       pool-1-thread-1 2016-05-31T03:51:50.736Z        org.javacs.JavaLanguageServer#onError   com.google.gson.stream.MalformedJsonException: Unterminated string at line 1 column 33710 path $.params.textDocument.text
com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Unterminated string at line 1 column 33710 path $.params.textDocument.text
        at com.google.gson.internal.Streams.parse(Streams.java:60)
        at com.google.gson.JsonParser.parse(JsonParser.java:84)
        at com.google.gson.JsonParser.parse(JsonParser.java:59)
        at io.typefox.lsapi.services.json.MessageJsonHandler.parseMessage(MessageJsonHandler.java:102)
        at io.typefox.lsapi.services.json.MessageJsonHandler.parseMessage(MessageJsonHandler.java:98)
        at io.typefox.lsapi.services.json.LanguageServerProtocol.handleMessage(LanguageServerProtocol.java:239)
        at io.typefox.lsapi.services.json.LanguageServerProtocol.listen(LanguageServerProtocol.java:164)
        at io.typefox.lsapi.services.json.LanguageServerProtocol$InputListener.run(LanguageServerProtocol.java:58)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: com.google.gson.stream.MalformedJsonException: Unterminated string at line 1 column 33710 path $.params.textDocument.text
        at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1574)
        at com.google.gson.stream.JsonReader.nextQuotedValue(JsonReader.java:1031)
        at com.google.gson.stream.JsonReader.nextString(JsonReader.java:827)
        at com.google.gson.internal.bind.TypeAdapters$29.read(TypeAdapters.java:722)
        at com.google.gson.internal.bind.TypeAdapters$29.read(TypeAdapters.java:743)
        at com.google.gson.internal.bind.TypeAdapters$29.read(TypeAdapters.java:743)
        at com.google.gson.internal.bind.TypeAdapters$29.read(TypeAdapters.java:743)
        at com.google.gson.internal.bind.TypeAdapters$29.read(TypeAdapters.java:718)
        at com.google.gson.internal.Streams.parse(Streams.java:48)
        ... 12 more
```

This happens consistently when I open VSCode with this file:

https://gist.github.com/georgewfraser/ed8dd384437a67692c7810fbdfd2c5f4

**Comment by georgewfraser** [comment]
Looking at the decompiled code in the debugger, it appears that inside LanguageServerProtocol you are doing 

```
InputStream in
byte[] bytes
int contentLength

in.read(bytes, 0, contentLength)
```

and then assuming that it actually read contentLength bytes, which it didn't, because `in` is a network socket and not everything was available yet.

**Comment by georgewfraser** [comment]
It has stopped happening since I downloaded a new version of 0.2-SNAPSHOT. 

_edit_ Nope, still happening with large files
